# This file was generated by GoReleaser. DO NOT EDIT.
cask "markgate" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "ccf41a1da8fba6161de06688474841b9c435e056aafb965e528e41f95d677ec3"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "65243888919624d6f2504918b37a238c89d5c84ee08cee4f603670ade9cf07c6"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "191d085c786bb1b8211f4a26783886640b098fbf6b37df3d170de8ce831ffa00"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3dadfb37a22d12e2fdf3c25411dfd1cca02306819a9e190886c8ee31ebc856e3"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "markgate"
  desc "State-cached gate primitive for hook managers"
  homepage "https://github.com/go-to-k/markgate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "markgate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/markgate"]
    end
  end

  # No zap stanza required

end
