# This file was generated by GoReleaser. DO NOT EDIT.
cask "markgate" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "9be27278e0a93f63d8bd5bf08742156e1962516421aa9700152d992585268d56"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "64f4f99ed7baa823c59ce60472a2bbdb74d7b334bc17797d9ba0300335045261"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2e3a2de8904c76d090f1a89c68064934748bf6cb67bcc46f3b6f4a3962bfb669"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "e500350857cbf27d082388bfbbbf8a596597bf486eea7d96a161468d802e797b"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "markgate"
  desc "State-cached gate primitive for hook managers"
  homepage "https://github.com/go-to-k/markgate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "markgate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/markgate"]
    end
  end

  # No zap stanza required

end
