# This file was generated by GoReleaser. DO NOT EDIT.
cask "markgate" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "2afebd8b1ab77cdf382ca6c7df395287872957fe81398b8e3998e141987be145"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c4d50f8b17086a0ebc17e41dc5bafca1bf61cf6dc1021228b046086dad12f850"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ebee812a872738d9fbda80b68a512f82c173df2a977c74017145c2a63606b5a0"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "f1d29ffb0f182390407295c452af4343d954fe97635bb2232651913f622b3dc2"
      url "https://github.com/go-to-k/markgate/releases/download/v#{version}/markgate_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "markgate"
  desc "State-cached gate primitive for hook managers"
  homepage "https://github.com/go-to-k/markgate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "markgate"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
        args: ["-dr", "com.apple.quarantine", "#{staged_path}/markgate"]
    end
  end

  # No zap stanza required

end
