# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cls3 < Formula
  desc "cls3"
  homepage "https://github.com/go-to-k/cls3"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-to-k/cls3/releases/download/v0.1.1/cls3_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "8e9b98afbe275441bee5630a4bb1504b6946bbe47695a37568f00a0b40d46902"

      def install
        bin.install "cls3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-to-k/cls3/releases/download/v0.1.1/cls3_0.1.1_Darwin_arm64.tar.gz"
      sha256 "da65a01c8b1a3a1528df7f563d17360634871ab3a15e39ca43800bcae8b6cf99"

      def install
        bin.install "cls3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-to-k/cls3/releases/download/v0.1.1/cls3_0.1.1_Linux_arm64.tar.gz"
      sha256 "69efdf8162a5035f08aa03b4191561057140c7be385edfd924fe6e4f276edb25"

      def install
        bin.install "cls3"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-to-k/cls3/releases/download/v0.1.1/cls3_0.1.1_Linux_x86_64.tar.gz"
      sha256 "948194403413815a8bed5a8cce7a084c14bf5bbd3955a730cc23e6ab55ed3c97"

      def install
        bin.install "cls3"
      end
    end
  end

  test do
    system "#{bin}/cls3 -v"
  end
end
