# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lamver < Formula
  desc "lamver"
  homepage "https://github.com/go-to-k/lamver"
  version "0.4.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/go-to-k/lamver/releases/download/v0.4.1/lamver_ 0.4.1_Darwin_x86_64.tar.gz"
      sha256 "e1a21a7a33cdc27d0e982680a21a3c546a5e064e79a788d7ef8ba74ea1487096"

      def install
        bin.install "lamver"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/go-to-k/lamver/releases/download/v0.4.1/lamver_ 0.4.1_Darwin_arm64.tar.gz"
      sha256 "7400f1006c357886a5792b18e9f863d4650feadc6e1a7aa92704c70721a5a3d9"

      def install
        bin.install "lamver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-to-k/lamver/releases/download/v0.4.1/lamver_ 0.4.1_Linux_arm64.tar.gz"
      sha256 "581dc3ec2d667af46aef35b61b2705cf4ff3f36f792c72985fb80c8a2e6cfc11"

      def install
        bin.install "lamver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-to-k/lamver/releases/download/v0.4.1/lamver_ 0.4.1_Linux_x86_64.tar.gz"
      sha256 "fb7657bdb4573cb97f4707070546a10809950645080fa10b20a054100bd51de3"

      def install
        bin.install "lamver"
      end
    end
  end

  test do
    system "#{bin}/lamver -v"
  end
end
