# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lamver < Formula
  desc "lamver"
  homepage "https://github.com/go-to-k/lamver"
  version "0.17.0"

  on_macos do
    on_intel do
      url "https://github.com/go-to-k/lamver/releases/download/v0.17.0/lamver_0.17.0_Darwin_x86_64.tar.gz"
      sha256 "f4494603bac69d2d72fd54e785e4456b6778acabb961289bd244ffdc97f03449"

      def install
        bin.install "lamver"
      end
    end
    on_arm do
      url "https://github.com/go-to-k/lamver/releases/download/v0.17.0/lamver_0.17.0_Darwin_arm64.tar.gz"
      sha256 "51bcf4a7977b5305ca8714e25c97fe0c0f6ca1efa2ed476b3cd61652a112b57f"

      def install
        bin.install "lamver"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-to-k/lamver/releases/download/v0.17.0/lamver_0.17.0_Linux_x86_64.tar.gz"
        sha256 "76218c417ad9686de706c5f04a15dbbef94a55d576f7900d91d5d4c745555adc"

        def install
          bin.install "lamver"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/go-to-k/lamver/releases/download/v0.17.0/lamver_0.17.0_Linux_arm64.tar.gz"
        sha256 "5b75294f017e9e126e43279d8dd8e016c957f1ca1e50fe122c6ecf2c8f89c591"

        def install
          bin.install "lamver"
        end
      end
    end
  end

  test do
    system "#{bin}/lamver -v"
  end
end
