# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lamver < Formula
  desc "lamver"
  homepage "https://github.com/go-to-k/lamver"
  version "0.4.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/go-to-k/lamver/releases/download/v0.4.0/lamver_0.4.0_Darwin_arm64.tar.gz"
      sha256 "da81c8201d9895fe6630dfb3f9e25850cb73f81fdcc4f70fb7f721721ad06afd"

      def install
        bin.install "lamver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-to-k/lamver/releases/download/v0.4.0/lamver_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "286215cb0f87a1e22cd6502d730c6f03f316bfa6e9116fa5ae7e02aebafe4764"

      def install
        bin.install "lamver"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/go-to-k/lamver/releases/download/v0.4.0/lamver_0.4.0_Linux_arm64.tar.gz"
      sha256 "55f7454f2c693eb05abb8bf6e157a4893220783c69b2c7cca4257b49ed1845bf"

      def install
        bin.install "lamver"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/go-to-k/lamver/releases/download/v0.4.0/lamver_0.4.0_Linux_x86_64.tar.gz"
      sha256 "2e8a0c1cd30019824d5bb39d94f323310026c708c43243c9e18b5e065bf6f486"

      def install
        bin.install "lamver"
      end
    end
  end

  test do
    system "#{bin}/lamver -v"
  end
end
